### ISSUE TITLE
Cannot run inference due to wrong cache path

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/Grapher#1]
Command
`python3 main.py --run inference --version 2 --default_root_dir ${STORAGE_DRIVE}/data/core/grapher/output --inference_input_text "Danielle Harris had a main role in Super`

Stacktrace
```
 Capers, a 98 minute long movie."
Traceback (most recent call last):
  File "/home/fkovacev/core/Grapher/main.py", line 209, in <module>
    main(args)
  File "/home/fkovacev/core/Grapher/main.py", line 139, in main
    grapher = LitGrapher.load_from_checkpoint(checkpoint_path=checkpoint_model_path)
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1561, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 61, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py", line 56, in _load
    return torch.load(f, map_location=map_location)  # type: ignore[arg-type]
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/pickle.py", line 1718, in load_build
    setstate(state)
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5.py", line 372, in __setstate__
    self.sp_model.Load(self.vocab_file)
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/newstorage4/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "/newstorage4/fkovacev/data/core/Grapher/cache/models--t5-large/snapshots/150ebc2c4b72291e770f58e6057481c8d2ed331a/spiece.model": No such file or directory Error #2
```

The main issue is that I moved the cache folder from the project folder to our data drive. However, pytorch_lightning expects the cache folder by default to be in the project directory. The cache directory needs to be set explicitly somewhere.

# Variable resolutions of the paths in main.py
checkpoint_model_path = args.checkpoint_dir/last.ckpt
checkpoint_model_path = args.eval_dir/checkpoints/last.ckpt
checkpoint_model_path = args.default_root_dir/args.dataset + '_version_' + args.version/checkpoints/last.ckpt
checkpoint_model_path = args.default_root_dir/args.dataset + '_version_' + args.version/checkpoints/last.ckpt
checkpoint_model_path = ${STORAGE_DRIVE}/data/core/grapher/output/webnlg_version_2/checkpoints/last.ckpt
checkpoint_model_path = /newstorage4/fkovacev/data/core/grapher/output/webnlg_version_2/checkpoints/last.ckpt

**Comment by GreenfishK** [comment]
I changed the cache directory in the hparams.yaml file but it did not have any effect.
I also copied the whole project directory into a new directory and executed main.py from the new directory and it still tries to load from `"/newstorage4/fkovacev/data/core/Grapher/cache/models--t5-large/snapshots/150ebc2c4b72291e770f58e6057481c8d2ed331a/spiece.model`.

**Comment by GreenfishK** [comment]
resolved
