### ISSUE TITLE
Score computation breaks due to NoneType passing to Evaluation_script_json.main(...)

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/Grapher#2]
During execution of train_class, at the end of the validation epoch, an error occurs while trying to compute the scores.

Stacktrace
```
creating reference xml  file : [/gpfs/data/fs72332/fkovacev/data/core/grapher/output/webnlg_model_variant=class/valid/ref_178_1.xml]
creating hypothesis xml file : [/gpfs/data/fs72332/fkovacev/data/core/grapher/output/webnlg_model_variant=class/valid/hyp_178_1.xml]
Traceback (most recent call last):
  File "/home/fs72332/fkovacev/core/Grapher/src/main.py", line 50, in <module>
    train.train(args, model_variant)
  File "/home/fs72332/fkovacev/core/Grapher/src/tasks/train.py", line 142, in train
    trainer.fit(model=grapher, datamodule=dm,
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 141, in run
    return self.on_run_end()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 253, in on_run_end
    self._on_evaluation_epoch_end()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 329, in _on_evaluation_epoch_end
    call._call_lightning_module_hook(trainer, hook_name)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/fs72332/fkovacev/core/Grapher/src/engines/grapher_lightning.py", line 130, in on_validation_epoch_end
    self.validation_step_outputs.append(val_outputs)
  File "/home/fs72332/fkovacev/core/Grapher/src/engines/grapher_lightning.py", line 222, in eval_epoch_end
    logging.info(f"Logging validation scores: Precision: {scores['Precision']}; Recall: {scores['Recall']}; F1: {scores['F1']}")
  File "/home/fs72332/fkovacev/core/Grapher/src/misc/utils.py", line 226, in compute_scores
    Evaluation_script_json.main(ref_fname, hyp_fname, scores_fname)
  File "/home/fs72332/fkovacev/core/Grapher/src/WebNLG_Text_to_triples/Evaluation_script_json.py", line 846, in main
    totalsemevallist, totalsemevallistpertag = calculateAllScores(newreflist, newcandlist)
  File "/home/fs72332/fkovacev/core/Grapher/src/WebNLG_Text_to_triples/Evaluation_script_json.py", line 476, in calculateAllScores
    results, results_per_tag = evaluaterefcand(reference, triple)
  File "/home/fs72332/fkovacev/core/Grapher/src/WebNLG_Text_to_triples/Evaluation_script_json.py", line 268, in evaluaterefcand
    newreflist, newcandlist = nonrefwords(newreflist, newcandlist, 1, ngramlength)
  File "/home/fs72332/fkovacev/core/Grapher/src/WebNLG_Text_to_triples/Evaluation_script_json.py", line 114, in nonrefwords
    newcandindex = list(range(findnewcand[0], findnewcand[1]+1))
TypeError: 'NoneType' object is not subscriptable
[rank: 1] Child process with PID 4171247 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
./train_class.sh: line 37: 4170939 Killed                  python3 main.py --run train --edges_as_classes 1 --dataset webnlg --pretrained_model t5-large --data_path ${STORAGE_DRIVE}/data/core/webnlg-dataset/release_v3.0/en --cache_dir ${STORAGE_DRIVE}/data/core/cache/grapher --num_data_workers 1 --every_n_epochs 1 --checkpoint_model_id -1 --max_nodes 8 --max_edges 7 --default_seq_len_node 20 --default_seq_len_edge 20 --batch_size 20 --lr 1e-4 --focal_loss_gamma 3 --dropout_rate 0.5 --num_layers 2 --eval_dump_only 0 --default_root_dir ${STORAGE_DRIVE}/data/core/grapher/output --accelerator gpu --max_epochs 100 --num_nodes 1 --num_sanity_val_steps 0 --fast_dev_run 0 --overfit_batches 0 --limit_train_batches 1.0 --limit_val_batches 1.0 --limit_test_batches 1.0 --accumulate_grad_batches 10 --log_every_n_steps 100 --check_val_every_n_epoch 1
```

**Comment by GreenfishK** [comment]
Issue has not appeared ever since
