### ISSUE TITLE
Error during execution of "sbatch train_gen.slrm": "piece id is out of range"

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/Grapher#3]
```
[nltk_data] Downloading package punkt to /gpfs/data/fs72332/fkovacev/d
[nltk_data]     ata/core/grapher/output/../lib/punkt...
[nltk_data] Downloading package punkt to /gpfs/data/fs72332/fkovacev/d
[nltk_data]     ata/core/grapher/output/../lib/punkt...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to /gpfs/data/fs72332/fkovacev/d
[nltk_data]     ata/core/grapher/output/../lib/punkt...
[nltk_data] Downloading package punkt to /gpfs/data/fs72332/fkovacev/d
[nltk_data]     ata/core/grapher/output/../lib/punkt...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data]   Package punkt is already up-to-date!
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-02-14 18:25:45 root INFO: Load training data into GraphDataset.
2024-02-14 18:25:45 root INFO: Load training data into GraphDataset.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-02-14 18:25:45 root INFO: Load training data into GraphDataset.
2024-02-14 18:25:45 root INFO: Load training data into GraphDataset.
2024-02-14 18:25:46 root INFO: Load validation data (dev) into GraphDataset.
2024-02-14 18:25:46 root INFO: Load validation data (dev) into GraphDataset.
2024-02-14 18:25:46 torch.distributed.nn.jit.instantiator INFO: Created a temporary directory at /tmp/tmp7119ph1k
2024-02-14 18:25:46 torch.distributed.nn.jit.instantiator INFO: Created a temporary directory at /tmp/tmp9tzsi_ny
2024-02-14 18:25:46 torch.distributed.nn.jit.instantiator INFO: Writing /tmp/tmp7119ph1k/_remote_module_non_scriptable.py
2024-02-14 18:25:46 torch.distributed.nn.jit.instantiator INFO: Writing /tmp/tmp9tzsi_ny/_remote_module_non_scriptable.py
2024-02-14 18:25:46 root INFO: Load validation data (dev) into GraphDataset.
2024-02-14 18:25:46 root INFO: Load validation data (dev) into GraphDataset.
2024-02-14 18:25:47 torch.distributed.nn.jit.instantiator INFO: Created a temporary directory at /tmp/tmpulho97vk
2024-02-14 18:25:47 torch.distributed.nn.jit.instantiator INFO: Created a temporary directory at /tmp/tmpa4s_kq2b
2024-02-14 18:25:47 torch.distributed.nn.jit.instantiator INFO: Writing /tmp/tmpulho97vk/_remote_module_non_scriptable.py
2024-02-14 18:25:47 torch.distributed.nn.jit.instantiator INFO: Writing /tmp/tmpa4s_kq2b/_remote_module_non_scriptable.py
2024-02-14 18:25:53 root INFO: NVIDIA A40
2024-02-14 18:25:53 root INFO: NVIDIA A40
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
2024-02-14 18:25:53 root INFO: NVIDIA A40
2024-02-14 18:25:53 root INFO: NVIDIA A40
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Added key: store_based_barrier_key:1 to store for rank: 1
2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Added key: store_based_barrier_key:1 to store for rank: 2
2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Added key: store_based_barrier_key:1 to store for rank: 3
2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Added key: store_based_barrier_key:1 to store for rank: 0
2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2024-02-14 18:25:54 torch.distributed.distributed_c10d INFO: Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2024-02-14 18:25:56 root INFO: Load training data into GraphDataset.
2024-02-14 18:25:56 root INFO: Load training data into GraphDataset.
2024-02-14 18:25:56 root INFO: Load training data into GraphDataset.
2024-02-14 18:25:56 root INFO: Load training data into GraphDataset.
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
┏━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓
┃   ┃ Name  ┃ Type    ┃ Params ┃
┡━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩
│ 0 │ model │ Grapher │  809 M │
└───┴───────┴─────────┴────────┘
Trainable params: 809 M                                                         
Non-trainable params: 0                                                         
Total params: 809 M                                                             
Total estimated model params size (MB): 3.2 K                                   
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
2024-02-14 18:26:14 torch.nn.parallel.distributed INFO: Reducer buckets have been rebuilt in this iteration.
2024-02-14 18:26:14 torch.nn.parallel.distributed INFO: Reducer buckets have been rebuilt in this iteration.
2024-02-14 18:26:14 torch.nn.parallel.distributed INFO: Reducer buckets have been rebuilt in this iteration.
2024-02-14 18:26:14 torch.nn.parallel.distributed INFO: Reducer buckets have been rebuilt in this iteration.
2024-02-14 18:38:17 root INFO: Iteration: 45; Rank: 2
2024-02-14 18:38:17 root INFO: Iteration: 45; Rank: 3
Traceback (most recent call last):
  File "/home/fs72332/fkovacev/core/Grapher/src/main.py", line 65, in <module>
    train.train(args, model_variant, device)
  File "/home/fs72332/fkovacev/core/Grapher/src/tasks/train.py", line 144, in train
    trainer.fit(model=grapher, 
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 402, in validation_step
    return self._forward_redirection(self.model, self.lightning_module, "validation_step", *args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 633, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 626, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/home/fs72332/fkovacev/core/Grapher/src/engines/grapher_lightning.py", line 137, in validation_step
    val_outputs = self.eval_step(batch, batch_idx, 'valid')
  File "/home/fs72332/fkovacev/core/Grapher/src/engines/grapher_lightning.py", line 192, in eval_step
    dec_pred = decode_graph(self.tokenizer, self.edge_classes, seq_nodes, seq_edges, self.edges_as_classes,
  File "/home/fs72332/fkovacev/core/Grapher/src/misc/utils.py", line 153, in decode_graph
    all_nodes = tokenizer._decode(nodes).split(tokenizer._decode(node_sep_id))
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 1001, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 982, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5.py", line 418, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/gpfs/data/fs72332/fkovacev/miniconda3/envs/data_science/lib/python3.10/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.
2024-02-14 18:38:21 root INFO: Iteration: 45; Rank: 0
srun: error: n3066-015: task 1: Exited with exit code 1
2024-02-14 18:38:41 root INFO: Validation scores: Precision: 0.15576360354037305; Recall: 0.16110102843315183; F1: 0.15784692302387401
2024-02-14 18:38:41 root INFO: Validation epoch ended
2024-02-14 18:38:42 root INFO: Validation scores: Precision: 0.15630313895357742; Recall: 0.16194940026207036; F1: 0.1584068251742881
2024-02-14 18:38:42 root INFO: Validation epoch ended
2024-02-14 18:38:46 root INFO: Validation scores: Precision: 0.15643454314714156; Recall: 0.1630577427821522; F1: 0.1588941813956956
2024-02-14 18:38:46 root INFO: Validation epoch ended

```

**Comment by GreenfishK** [comment]
Issue has not appeared ever since
